name: 🍎 macOS Builds

on:
  push:
    branches:
      - main
  pull_request:

env:
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  EXPORT_NAME: model_explorer_

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-deploy
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor macOS (target=editor,deploy=true,deploy-platform=macos,deploy-platform-target=template_release)
            cache-name: macos-editor-deploy-macos-template-release
            target: editor
            tests: false
            sconsflags: use_llvm=yes linker=gold deprecate=no
            doc-test: false
            bin: "./bin/godot.osx.editor.x86_64.llvm"
            deploy-bin: "./bin/godot.osx.template_release.x86_64.llvm"
            proj-conv: false
            artifact: true
            platform: osx
            deploy: true
            deploy-platform: macos
            deploy-platform-target: template_release

    steps:
      - uses: actions/checkout@v3

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Set up .NET Sdk
        uses: actions/setup-dotnet@v2
        if: ${{ matrix.build-mono }}
        with:
          dotnet-version: "6.0.x"

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}
          deploy: ${{ matrix.deploy }}
          deploy-platform: ${{ matrix.deploy-platform }}
          deploy-platform-target: ${{ matrix.deploy-platform-target }}

      - name: Export Game
        if: ${{ matrix.deploy }}
        run: |
          mkdir -p .godot/editor .godot/imported export_linux
          chmod +x ${{ matrix.bin }}
          ${{ matrix.bin }} --headless --xr-mode off --export-pack Linux  `pwd`/vsk_model_explorer_${{ matrix.deploy-platform }}.pck --path .
      - name: Prepare artifacts
        if: ${{ matrix.deploy && matrix.deploy-platform == 'windows' }}
        run: |
          rm -rf vsk_model_explorer_${{ matrix.deploy-platform }}
          export TARGET=vsk_model_explorer_${{ matrix.deploy-platform }}
          mkdir -p $TARGET
          cp -rf ${{ matrix.deploy-bin }} $TARGET/vsk_model_explorer_${{ matrix.deploy-platform }}.exe
          cp -rf vsk_model_explorer_${{ matrix.deploy-platform }}.pck $TARGET/vsk_model_explorer_${{ matrix.deploy-platform }}.pck
          7z a -r $TARGET.zip $TARGET
        shell: bash

      - name: Prepare artifacts
        if: ${{ matrix.deploy && matrix.deploy-platform != 'windows' }}
        run: |
          rm -rf vsk_model_explorer_${{ matrix.deploy-platform }}
          export TARGET=vsk_model_explorer_${{ matrix.deploy-platform }}
          mkdir -p $TARGET
          cp -rf ${{ matrix.deploy-bin }} $TARGET/vsk_model_explorer_${{ matrix.deploy-platform }}
          cp -rf vsk_model_explorer_${{ matrix.deploy-platform }}.pck $TARGET/vsk_model_explorer_${{ matrix.deploy-platform }}.pck
        shell: bash

      - name: Upload Godot Artifact Export
        if: ${{ matrix.deploy }}
        uses: actions/upload-artifact@v3
        with:
          name: vsk_model_explorer_${{ matrix.deploy-platform }}_x86_64
          path: |
            vsk_model_explorer_${{ matrix.deploy-platform }}

      - name: Generate C# glue
        if: ${{ matrix.build-mono }}
        run: |
          ${{ matrix.bin }} --headless --generate-mono-glue ./modules/mono/glue || true

      - name: Build .NET solutions
        if: ${{ matrix.build-mono }}
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd

      # Execute unit tests for the editor
      - name: Unit tests
        if: ${{ matrix.tests }}
        run: |
          ${{ matrix.bin }} --version
          ${{ matrix.bin }} --help
          ${{ matrix.bin }} --test --headless

      # Check class reference
      - name: Check for class reference updates
        if: ${{ matrix.doc-test }}
        run: |
          echo "Running --doctool to see if this changes the public API without updating the documentation."
          echo -e "If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.\n\n"
          ${{ matrix.bin }} --doctool --headless 2>&1 > /dev/null || true
          git diff --color --exit-code && ! git ls-files --others --exclude-standard | sed -e 's/^/New doc file missing in PR: /' | grep 'xml$'

      # Test 3.x -> 4.x project converter
      - name: Test project converter
        if: ${{ matrix.proj-conv }}
        run: |
          mkdir -p converter_test
          cd converter_test
          touch project.godot
          ${{ matrix.bin }} --headless --validate-conversion-3to4
          cd ..
          rm converter_test -rf

      # Download and extract zip archive with project, folder is renamed to be able to easy change used project
      - name: Download test project
        if: ${{ matrix.proj-test }}
        run: |
          wget https://github.com/godotengine/regression-test-project/archive/4.0.zip
          unzip 4.0.zip
          mv "regression-test-project-4.0" "test_project"

      # Editor is quite complicated piece of software, so it is easy to introduce bug here
      - name: Open and close editor (Vulkan)
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ${{ matrix.bin }} --audio-driver Dummy --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      - name: Open and close editor (GLES3)
        if: ${{ matrix.proj-test }}
        run: |
          DRI_PRIME=0 xvfb-run ${{ matrix.bin }} --audio-driver Dummy --rendering-driver opengl3 --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Run test project
      - name: Run project
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ${{ matrix.bin }} 40 --audio-driver Dummy --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Checkout godot-cpp
      - name: Checkout godot-cpp
        if: ${{ matrix.godot-cpp-test }}
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot-cpp
          submodules: "recursive"
          path: "godot-cpp"

      # Dump GDExtension interface and API
      - name: Dump GDExtension interface and API for godot-cpp build
        if: ${{ matrix.godot-cpp-test }}
        run: |
          ${{ matrix.bin }} --headless --dump-gdextension-interface --dump-extension-api
          cp -f gdextension_interface.h godot-cpp/gdextension/
          cp -f extension_api.json godot-cpp/gdextension/

      # Build godot-cpp test extension
      - name: Build godot-cpp test extension
        if: ${{ matrix.godot-cpp-test }}
        run: |
          cd godot-cpp/test
          scons target=template_debug dev_build=yes
          cd ../..

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          chmod +x godot/bin/godot.* || true
          chmod +x godot/bin/libgodot.* || true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
